name: hospital_staff_management
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  firebase_core: ^2.16.0
  firebase_database: ^10.2.6
  equatable: ^2.0.5
  cupertino_will_pop_scope: ^1.2.1
  get: ^4.6.5
  go_router: ^11.1.2
  firebase_storage: ^11.2.7
  image_picker: ^1.0.4
  intl: ^0.18.0
  avatar_glow: ^2.0.2
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  expandable: ^5.0.1
  shared_preferences: ^2.2.1
  get_it: ^7.6.4
  logger: ^1.1.0
  omni_datetime_picker: ^1.0.9
  full_screen_image: ^2.0.0
  firebase_messaging: ^14.7.0
  flutter_local_notifications: ^16.1.0
  http: ^1.1.0
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/med.jpg"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 900
